<?php

return [
    'types' => [
        'preticket' => 'Pre-ticket (mesero)',
        'kitchen'   => 'Comanda cocina',
        'receipt'   => 'Ticket de cobro',
    ],

    'placeholders' => [
        'preticket' => [
            '{{restaurant_name}}' => 'Nombre del restaurante',
            '{{title}}'           => 'Título del ticket',
            '{{subtitle}}'        => 'Subtítulo',
            '{{table}}'           => 'Mesa / nombre de mesa',
            '{{waiter}}'          => 'Nombre del mesero',
            '{{datetime}}'        => 'Fecha y hora',
            '{{subtotal}}'        => 'Subtotal (COP)',
            '{{tax}}'             => 'IVA (COP)',
            '{{total}}'           => 'Total (COP)',
        ],
    ],

    'defaults' => [
        'preticket' => [
            'title'                => 'PRE-TICKET',
            'subtitle'             => 'NO ES FACTURA — COP',
            'extra_header_lines'   => [],
            'footer_lines'         => [],
            'show_restaurant_name' => true,
            'show_table'           => true,
            'table_large'          => false,
            'show_waiter'          => true,
            'show_datetime'        => true,
            'show_items'           => true,
            'show_item_subtotal'   => true,
            'show_modifiers'       => true,
            'show_item_comments'   => true,
            'show_subtotal'        => false,
            'show_tax'             => false,
            'show_total'           => true,
            'title_bold'           => true,
            'total_bold'           => true,
            'printer_purpose'      => 'receipt',
        ],
        'receipt' => [
            'title'                => 'FACTURA',
            'subtitle'             => '',
            'extra_header_lines'   => [],
            'footer_lines'         => ['¡Gracias por su visita!'],
            'show_restaurant_name' => true,
            'show_table'           => true,
            'table_large'          => false,
            'show_waiter'          => false,
            'show_datetime'        => true,
            'show_items'           => true,
            'show_item_subtotal'   => true,
            'show_modifiers'       => false,
            'show_item_comments'   => false,
            'show_subtotal'        => true,
            'show_tax'             => true,
            'show_total'           => true,
            'title_bold'           => true,
            'total_bold'           => true,
            'printer_purpose'      => 'receipt',
        ],
        'kitchen' => [
            'title'                => 'COCINA',
            'subtitle'             => '',
            'extra_header_lines'   => [],
            'footer_lines'         => [],
            'show_restaurant_name' => true,
            'show_table'           => true,
            'table_large'          => true,
            'show_waiter'          => true,
            'show_kitchen_sender'  => true,
            'show_datetime'        => true,
            'show_items'           => true,
            'show_item_subtotal'   => false,
            'show_modifiers'       => true,
            'show_item_comments'   => true,
            'show_subtotal'        => false,
            'show_tax'             => false,
            'show_total'           => false,
            'title_bold'           => true,
            'total_bold'           => false,
            'printer_purpose'      => 'kitchen',
        ],
    ],
];
